name: Update releated themes
on:
  # Triggers the workflow on releases
  release:
    types: [published]
jobs:
  update:
    name: Update themes
    runs-on: ubuntu-latest
    steps:
      - name: trigger Job
        uses: appleboy/gitlab-ci-action@master
        with:
          token: ${{ secrets.TOKEN }}
          project_id: ${{ secrets.PROJECT_ID }}
          ref: master
          debug: true
